spring:
  application:
    name: order-service

  profiles:
    active: docker

server:
  port: 8080
  error:
    include-message: always

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /order-swagger-ui.html
    enabled: true
    doc-expansion: list
    operations-sorter: alpha
